// editor/src/components/Configuration.vue
<script setup lang="ts">
import { path } from '@tauri-apps/api'
import { invoke } from '@tauri-apps/api/core'
import { listen } from '@tauri-apps/api/event'
import { appDataDir } from '@tauri-apps/api/path'
import { open } from '@tauri-apps/plugin-dialog'
import { openPath } from '@tauri-apps/plugin-opener'
import { FOLDER } from '../lib/fileOperations'

const levelStore = useLevelStore()

const openFolder = async () => {
	const dir = await appDataDir()
	openPath(await path.join(dir, FOLDER))
}

const saveMode = ref<'local' | 'github'>('local')
const pushingChanges = ref<'in_progress' | 'success' | null>(null)

const pullLatest = async () => {
	const dir = await appDataDir()
	invoke('pull_latest_command', { repoPath: await path.join(dir, FOLDER) })
}
const localDir = useLocalStorage<string | null>('localDir', null)
const loggedIn = ref(false)

const save = async () => {
	await levelStore.save(localDir.value)
}

const pushChanges = async () => {
	if (pushingChanges.value !== null) return
	pushingChanges.value = 'in_progress'
	await pullLatest()
	await save()
	try {
		if (saveMode.value === 'github') {
			await invoke('create_pr_command', {
				repoPath: await path.join(await appDataDir(), FOLDER),
				baseBranch: 'main',
				commitMessage: 'Update level',
				prTitle: 'Update level',
				prBody: 'Update level',
			})
			// eslint-disable-next-line no-alert
			alert('Changes pushed successfully!')
		}
		pushingChanges.value = 'success'
		setTimeout(() => pushingChanges.value = null, 2000)
	} catch (err) {
		console.error(err)
		// eslint-disable-next-line no-alert
		alert(`Failed to push changes: ${err}`)
	}
}
const configModalOpen = ref(false)
const loading = ref(false)
const userCode = ref('')
const verificationUri = ref('')
async function startLogin() {
	loading.value = true

	// Listen for device flow start
	const unlistenStart = await listen('device_flow_start', (event) => {
		const payload = event.payload as { user_code: string, verification_uri: string }
		userCode.value = payload.user_code
		verificationUri.value = payload.verification_uri
	})

	// Listen for success
	const unlistenSuccess = await listen('device_flow_success', () => {
		loading.value = false
		loggedIn.value = true
		configModalOpen.value = false
		unlistenStart()
		unlistenSuccess()
	})

	// Listen for errors
	const unlistenError = await listen('device_flow_error', (event) => {
		// eslint-disable-next-line no-alert
		alert(`Login failed: ${event.payload}`)
		loading.value = false
		unlistenStart()
		unlistenSuccess()
		unlistenError()
	})

	// Trigger Tauri command
	await invoke('start_github_device_flow')
}

const selectFolder = async () => {
	const path = await open({
		multiple: false,
		directory: true,
	})
	localDir.value = path
}
</script>

<template>
	<NCard size="small">
		<NInputGroup style="display: grid;grid-template-columns: 1fr 1fr 1fr">
			<NButton @click="openFolder">
				<template #icon>
					<NIcon>
						<fa-folder-open />
					</NIcon>
				</template>
			</NButton>
			<NButton @click="pushChanges">
				<template #icon>
					<NIcon>
						<template v-if="pushingChanges === null">
							<fa-save v-if="saveMode === 'local'" />
							<fa-cloud-arrow-up v-else />
						</template>
						<fa-check v-else-if="pushingChanges === 'success'" />
						<NSpin v-else-if="pushingChanges === 'in_progress'" :size="15" />
					</NIcon>
				</template>
			</NButton>
			<NButton @click="configModalOpen = !configModalOpen">
				<template #icon>
					<NIcon>
						<fa-gear />
					</NIcon>
				</template>
			</NButton>
		</NInputGroup>
	</NCard>
	<NModal
		v-if="configModalOpen"
		preset="card"
		:show="true"
		style="width: fit-content"
	>
		<div style="display:grid;grid-template-columns: 1fr 1fr; gap: 1rem">
			<NCard title="Github" :bordered="saveMode === 'github'">
				<template #header-extra>
					<NButton
						:disabled="saveMode === 'github'"
						@click=" saveMode = 'github'"
					>
						Activate
					</NButton>
				</template>
				<NSpace vertical>
					<NButton :disabled="loading || saveMode !== 'github'" @click="startLogin">
						<fab-github />
						{{ loading ? 'Waiting for authorization...' : 'Login with GitHub' }}
					</NButton>

					<div v-if="userCode">
						<p>
							Go to
							<a :href="verificationUri" target="_blank">{{ verificationUri }}</a>
							and enter the code:
						</p>
						<h2>{{ userCode }}</h2>
					</div>
					<NButton @click="pullLatest">
						<template #icon>
							<NIcon>
								<fa-cloud-arrow-down />
							</NIcon>
						</template>
						Pull latest
					</NButton>
				</NSpace>
			</NCard>
			<NCard title="Local" :bordered="saveMode === 'local'">
				<template #header-extra>
					<NButton
						:disabled="saveMode === 'local'"
						@click="saveMode = 'local'"
					>
						Activate
					</NButton>
				</template>
				<NSpace vertical>
					<NButton with-icon @click="selectFolder">
						<template #icon>
							<NIcon>
								<fa-folder-closed />
							</NIcon>
						</template>

						Select folder
					</NButton>
					<NEllipsis style="width:10rem">
						{{ localDir }}
					</NEllipsis>
				</NSpace>
			</NCard>
		</div>
	</NModal>
</template>

<style scoped></style>

// editor/src/oldcomponents/Configuration.tsx
// import type { Accessor, Setter } from 'solid-js'
// import type { Atom } from 'solid-use/atom'
// import { faGithub } from '@fortawesome/free-brands-svg-icons'
// import { faCheck, faCloudArrowDown, faCloudArrowUp, faDownload, faExclamationTriangle, faFolderClosed, faFolderOpen, faGear, faSave, faSpinner } from '@fortawesome/free-solid-svg-icons'
// import { makePersisted } from '@solid-primitives/storage'
// import { path } from '@tauri-apps/api'
// import { invoke } from '@tauri-apps/api/core'
// import { listen } from '@tauri-apps/api/event'
// import { appDataDir } from '@tauri-apps/api/path'
// import { open } from '@tauri-apps/plugin-dialog'
// import { BaseDirectory, exists, mkdir, remove } from '@tauri-apps/plugin-fs'
// import { openPath } from '@tauri-apps/plugin-opener'
// import Fa from 'solid-fa'
// import { createMemo, createSignal, onCleanup, onMount, Show } from 'solid-js'
// import { css } from 'solid-styled'
// import atom from 'solid-use/atom'
// import { FOLDER } from '../lib/fileOperations'
// import { Modal } from './Modal'

// export default function GithubDeviceLogin({ onLoggedIn, disabled }: { disabled: Accessor<boolean>, onLoggedIn: () => void }) {
// 	const [userCode, setUserCode] = createSignal('')
// 	const [verificationUri, setVerificationUri] = createSignal('')
// 	const [loading, setLoading] = createSignal(false)

	// async function startLogin() {
	// 	setLoading(true)

	// 	// Listen for device flow start
	// 	const unlistenStart = await listen('device_flow_start', (event) => {
	// 		const payload = event.payload as { user_code: string, verification_uri: string }
	// 		setUserCode(payload.user_code)
	// 		setVerificationUri(payload.verification_uri)
	// 	})

	// 	// Listen for success
	// 	const unlistenSuccess = await listen('device_flow_success', () => {
	// 		setLoading(false)
	// 		onLoggedIn()f
	// 		unlistenStart()
	// 		unlistenSuccess()
	// 	})

	// 	// Listen for errors
	// 	const unlistenError = await listen('device_flow_error', (event) => {
	// 		// eslint-disable-next-line no-alert
	// 		alert(`Login failed: ${event.payload}`)
	// 		setLoading(false)
	// 		unlistenStart()
	// 		unlistenSuccess()
	// 		unlistenError()
	// 	})

	// 	// Trigger Tauri command
	// 	await invoke('start_github_device_flow')
	// }

// 	return (
// 		<>
			// <button with-icon onClick={startLogin} disabled={loading() || disabled()}>
			// 	<Fa icon={faGithub}></Fa>
			// 	{loading() ? 'Waiting for authorization...' : 'Login with GitHub'}
			// </button>

			// {userCode() && (
			// 	<div>
			// 		<p>
			// 			Go to
			// 			<a href={verificationUri()} target="_blank">{verificationUri()}</a>
			// 			{' '}
			// 			and enter the code:
			// 		</p>
			// 		<h2>{userCode()}</h2>
			// 	</div>
			// )}
// 		</>
// 	)
// }
// export function Configuration({ reload, repoCloned, saveLevel, localFolder, setLocalFolder }: {
// 	reload: () => void
// 	repoCloned: Atom<boolean>
// 	saveLevel: () => Promise<void>
// 	localFolder: Accessor<string | null>
// 	setLocalFolder: Setter<string | null>
// }) {
// 	const openFolder = async () => {
// 		const dir = await appDataDir()
// 		openPath(await path.join(dir, FOLDER))
// 	}
// 	const authModalOpen = atom(false)
// 	const [saveMode, setSaveMode] = makePersisted(createSignal<'local' | 'github'>('github'))

// 	const status = atom<'cloning' | 'done' | null>(null)
// 	const error = atom<string | null>(null)
// 	const progress = atom(0)
// 	const loggedIn = atom(false)
// 	const downloadModalOpen = atom(false)

// 	onMount(async () => {
// 		const unListed = await listen<boolean>('login_valid', (e) => {
// 			loggedIn(e.payload)
// 			unListed()
// 		})
// 		invoke('validate_github_token_command')
// 	})

// 	const pullLatest = async () => {
// 		const dir = await appDataDir()
// 		invoke('pull_latest_command', { repoPath: await path.join(dir, FOLDER) })
// 	}

// 	const cloneRepo = async () => {
// 		status('cloning')
// 		error(null)
// 		progress(0)

// 		const dir = await appDataDir()

// 		// --- Set up event listeners ---
// 		const unlistenProgress = await listen<number>('clone_progress', (event) => {
// 			progress(event.payload)
// 		})

// 		const unlistenDone = await listen<string>('clone_done', () => {
// 			status('done')
// 			progress(100)
// 			setTimeout(() => {
// 				status(null)
// 				progress(0)
// 			}, 2000)
// 		})

// 		const unlistenError = await listen<string>('clone_error', (event) => {
// 			console.error('❌', event.payload)
// 			error(event.payload)
// 		})

// 		try {
// 			const folderExists = await exists(FOLDER, { baseDir: BaseDirectory.AppData })
// 			if (folderExists) await remove(FOLDER, { baseDir: BaseDirectory.AppData, recursive: true })
// 			await mkdir(FOLDER, { baseDir: BaseDirectory.AppData })

// 			await invoke('clone_repo_command', {
// 				repoPath: await path.join(dir, FOLDER),
// 			})
// 			reload()
// 		} catch (err) {
// 			console.error('❌ Failed to start clone:', err)
// 			error(String(err))
// 		}

// 		onCleanup(() => {
// 			unlistenProgress()
// 			unlistenDone()
// 			unlistenError()
// 		})
// 		downloadModalOpen(false)
// 	}
// 	const pushingChanges = atom<'in_progress' | 'success' | null>(null)

// 	const pushChanges = async () => {
// 		if (pushingChanges() !== null) return
// 		pushingChanges('in_progress')
// 		await pullLatest()
// 		await saveLevel()
// 		try {
// 			if (saveMode() === 'github') {
// 				await invoke('create_pr_command', {
// 					repoPath: await path.join(await appDataDir(), FOLDER),
// 					baseBranch: 'main',
// 					commitMessage: 'Update level',
// 					prTitle: 'Update level',
// 					prBody: 'Update level',
// 				})
// 				// eslint-disable-next-line no-alert
// 				alert('Changes pushed successfully!')
// 			}
// 			pushingChanges('success')
// 			setTimeout(() => pushingChanges(null), 2000)
// 		} catch (err) {
// 			console.error(err)
// 			// eslint-disable-next-line no-alert
// 			alert(`Failed to push changes: ${err}`)
// 		}
// 	}

// 	const openDownloadModal = async () => {
// 		if (repoCloned()) {
// 			downloadModalOpen(true)
// 		} else {
// 			downloadModalOpen(true)
// 			await cloneRepo()
// 			repoCloned(true)
// 		}
// 	}

	// const selectFolder = async () => {
	// 	const path = await open({
	// 		multiple: false,
	// 		directory: true,
	// 	})
	// 	setLocalFolder(path)
	// }

// 	css/* css */`
// 	.configuration-title{
// 		display: grid;
// 		place-items: center;
// 	}
// 	.icon-container {
// 		display: flex;
// 		place-items: center;
// 		gap: 0.5rem;
// 	}
// 	.download-button{
// 		display: grid;
// 		place-items: center;
// 		width: 100%;
// 	}
// 	.error {
// 		padding: 0.5rem;
// 		border: solid 2px red;
// 		color: red;
// 		margin: 0.5rem;
// 	}
// 	.progress{
// 		display: flex;
// 		padding: 0.5rem;
// 		gap: 0.5rem;
// 		place-items:center;
// 	}

// 	.close-button{
// 		position: absolute;
// 		top:0.5rem;
// 		right: 0.5rem;
// 		font-size: 1.5rem;
// 		width: 1.5rem;
// 		height: 1.5rem;
// 		cursor: pointer;
// 	}
// 	.close-button:hover{
// 		color: grey;
// 	}
// 	.token-input{
// 		display: grid;
// 		grid-template-columns: 1fr auto;
// 		gap: 1rem;
// 	}
// 	.config-buttons{
// 		display: grid;
// 		grid-template-columns: 1fr 1fr 1fr 1fr;
// 	}
// 	@keyframes fa-spin{
// 		0% {
//     		transform: rotate(0deg);
// 		}
// 		100% {
// 			transform: rotate(1turn);
// 		}
// 	}
// 	.spinner{
// 		animation-name: fa-spin;
//     	animation-direction: normal;
//     	animation-duration: 1.5s;
//     	animation-iteration-count: infinite;
//     	animation-timing-function: steps(8);
// 	}
// 	.login-option-container{
// 		display: grid;
// 		gap: 1rem;
// 		align-items: center;
// 		padding: 0 2rem 2rem 2rem;
// 	}
// 	`

// 	const disabledGithubLogin = createMemo(() => saveMode() !== 'github')
// 	return (
// 		<>
// 			<section class="config-buttons button-group">
// 				<button title="open folder" onClick={openFolder}>
// 					<Fa size="lg" icon={faFolderOpen}></Fa>
// 				</button>
// 				<button onClick={pushChanges} title="Upload changes">
// 					<Show when={pushingChanges() === null}>
// 						<Fa size="lg" icon={saveMode() === 'github' ? faCloudArrowUp : faSave}></Fa>
// 					</Show>
// 					<Show when={pushingChanges() === 'success'}>
// 						<Fa size="lg" icon={faCheck}></Fa>
// 					</Show>
// 					<Show when={pushingChanges() === 'in_progress'}>
// 						<div class="spinner">
// 							<Fa size="lg" icon={faSpinner}></Fa>
// 						</div>
// 					</Show>
// 				</button>
// 				<Modal
// 					closable
// 					title="Select save method"
// 					trigger={(
// 						<button onClick={() => authModalOpen(!authModalOpen())}>
// 							<Fa size="lg" icon={faGear} color={saveMode() === 'github' && !loggedIn() ? 'red' : 'white'}></Fa>
// 						</button>
// 					)}
// 					open={authModalOpen}
// 				>
					// <div style="display:grid;grid-template-columns: auto auto; gap: 2rem">
					// 	<div>
					// 		<section class="login-option-container">
					// 			<div class="title">Github</div>
					// 			<GithubDeviceLogin
					// 				disabled={disabledGithubLogin}
					// 				onLoggedIn={() => {
					// 					loggedIn(true)
					// 					authModalOpen(false)
					// 				}}
					// 			/>
					// 			<button with-icon onClick={pullLatest}>
					// 				<Fa icon={faCloudArrowDown}></Fa>
					// 				Pull latest
					// 			</button>
					// 			<button
					// 				onClick={() => setSaveMode('github')}
					// 				disabled={saveMode() === 'github'}
					// 			>
					// 				Activate
					// 			</button>
					// 		</section>
					// 	</div>
					// 	<div>
					// 		<section class="login-option-container">
					// 			<div class="title">Local</div>
					// 			<button with-icon onClick={selectFolder}>
					// 				<Fa icon={faFolderClosed}></Fa>
					// 				Select folder
					// 			</button>
					// 			{localFolder()}
					// 			<button
					// 				disabled={saveMode() === 'local'}
					// 				onClick={() => setSaveMode('local')}
					// 			>
					// 				Activate
					// 			</button>
					// 		</section>
					// 	</div>
// 					</div>
// 				</Modal>
// 				<Modal
// 					trigger={(
// 						<button onClick={openDownloadModal}>
// 							<Fa size="lg" icon={faDownload} color={repoCloned() ? 'white' : 'red'}></Fa>
// 						</button>
// 					)}
// 					open={downloadModalOpen}
// 				>
// 					<Show when={status() === null}>
// 						<div>You will lose all your changes</div>
// 						<div>Are you sure you want to continue?</div>
// 						<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem;">
// 							<button onClick={() => downloadModalOpen(false)}>Cancel</button>
// 							<button onClick={cloneRepo}>Download repo</button>
// 						</div>
// 					</Show>
// 					<Show when={status() !== null}>
// 						<Show when={error()}>
// 							<div class="error">
// 								<div class="icon-container">
// 									<Fa icon={faExclamationTriangle}></Fa>
// 									Error
// 								</div>
// 								{error()}
// 								<button onClick={cloneRepo}>Retry</button>
// 							</div>
// 						</Show>
// 						<Show when={status() && !error()}>
// 							<div class="progress">
// 								<Fa icon={faSpinner} pulse></Fa>
// 								<div>
// 									{progress().toFixed(0)}
// 									%
// 								</div>
// 								<div>{status()}</div>
// 							</div>
// 						</Show>
// 					</Show>
// 				</Modal>
// 			</section>

// 		</>
// 	)
// }
